name: release_to_npm
on:
  release:
    types: [ created ]

jobs:

  sync_badges:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
      
      - run: |
          rm -rf .ci_badges
          npx setup-gh-badges
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .ci_badges
          git commit -m "[CI:deploy] sync_badges job"

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: badges_artifact
          path: .ci_badges

  build_docs:
    runs-on: ubuntu-18.04
    needs: sync_badges
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
      
      - run: |
          npm i typescript -g
          npx typedoc
          touch docs/.nojekyll

      - uses: actions/download-artifact@v2
        with:
          name: badges_artifact
          path: docs/.ci_badges
          
      - uses: actions/upload-artifact@v2
        with:
          name: docs_artifact
          path: docs/**/*

  sync_docs:
    runs-on: ubuntu-18.04
    needs: build_docs
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - run: rm -rf ./**/*

      - uses: actions/download-artifact@v2
        with:
          name: docs_artifact
          path: ./

      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "[CI:deploy] sync_docs job"

      - uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_and_publish:
    runs-on: ubuntu-18.04
    needs: sync_docs
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/

      - run: |
          npm i
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}