name: release_to_npm
on:
  release:
    types: [ created ]

jobs:

  sync_docs_and_badges:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
      
      - run: |
          rm -rf .ci_badges
          yarn add setup-gh-badges
          npx sync-badges
          rm -rf docs
          yarn docs
          cp -r .ci_badges docs/.ci_badges
          echo "# navigate into the build output directory..."
          cd docs
          touch .nojekyll #allow URLs starting/ending with _
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .ci_badges docs
          git commit -m "[CI:deploy] sync_docs_and_badges job"

      - uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_and_publish:
    runs-on: ubuntu-18.04
    needs: sync_docs_and_badges
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/

      - run: |
          yarn
          yarn build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}